-- Flyway migration script
-- Version: 1
-- Description: Create initial tables for SmartVolt application

-- User table (base class for EvDriver and StationOperator)
CREATE TABLE app_user (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    email VARCHAR(255) UNIQUE, -- Emails should be unique
    password VARCHAR(255),
    roles VARCHAR(255)[]
);

-- EvDriver table (inherits from app_user)
CREATE TABLE ev_driver (
    user_id BIGINT PRIMARY KEY,
    vehicle_plate VARCHAR(255),
    CONSTRAINT fk_ev_driver_app_user FOREIGN KEY (user_id) REFERENCES app_user(user_id) ON DELETE CASCADE
);

-- StationOperator table (inherits from app_user)
CREATE TABLE station_operator (
    user_id BIGINT PRIMARY KEY,
    CONSTRAINT fk_station_operator_app_user FOREIGN KEY (user_id) REFERENCES app_user(user_id) ON DELETE CASCADE
);

-- ChargingStation table
CREATE TABLE charging_station (
    station_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    address VARCHAR(255),
    availability BOOLEAN,
    operator_id BIGINT,
    CONSTRAINT fk_charging_station_operator FOREIGN KEY (operator_id) REFERENCES station_operator(user_id) ON DELETE CASCADE
);

-- ChargingSlot table
CREATE TABLE charging_slot (
    slot_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    is_locked BOOLEAN,
    price_perkwh DOUBLE PRECISION,
    power DOUBLE PRECISION,
    charging_speed VARCHAR(255),
    station_id BIGINT,
    CONSTRAINT fk_charging_slot_station FOREIGN KEY (station_id) REFERENCES charging_station(station_id) ON DELETE CASCADE
);

-- Booking table
CREATE TABLE booking (
    booking_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_id BIGINT,
    slot_id BIGINT,
    start_time TIMESTAMP,
    status VARCHAR(255),
    cost DOUBLE PRECISION,
    CONSTRAINT fk_booking_driver FOREIGN KEY (driver_id) REFERENCES ev_driver(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_booking_slot FOREIGN KEY (slot_id) REFERENCES charging_slot(slot_id) ON DELETE CASCADE
);

-- ChargingSession table
CREATE TABLE charging_session (
    session_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    energy_delivered DOUBLE PRECISION,
    booking_id BIGINT UNIQUE, -- OneToOne relationship with Booking
    CONSTRAINT fk_charging_session_booking FOREIGN KEY (booking_id) REFERENCES booking(booking_id) ON DELETE CASCADE
);

-- Payment table
CREATE TABLE payment (
    payment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_id BIGINT, -- ManyToOne relationship with EvDriver
    booking_id BIGINT UNIQUE, -- OneToOne relationship with Booking
    CONSTRAINT fk_payment_driver FOREIGN KEY (driver_id) REFERENCES ev_driver(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_payment_booking FOREIGN KEY (booking_id) REFERENCES booking(booking_id) ON DELETE CASCADE
);
