repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml                  # Check yaml files for syntax errors
        name: Check YAML
      - id: end-of-file-fixer           # Enforce a newline at the end of files
        name: End of File Fixer
      - id: trailing-whitespace         # Remove trailing whitespace
        name: Trailing Whitespace Fixer
      - id: check-added-large-files     # Prevent large files from being added
        name: Check Added Large Files
        args: ['--maxkb=100']           # Set max file size to 100KB
      - id: check-merge-conflict        # Check for merge conflict markers
        name: Check Merge Conflict
      - id: check-case-conflict       # Check for case conflicts in filenames
        name: Check Case Conflict
      - id: no-commit-to-branch       # Prevent commits to specific branches
        name: No Commit to "main" or "dev"
        args: ['--branch', 'main', '--branch', 'dev']
  - repo: local
    hooks:
      - id: mvn-spotless-check
        name: Maven Spotless - check
        entry: bash -c "cd smartvolt && mvn spotless:check"
        language: system
        types: [java]

      - id: mvn-spotless-apply
        name: Maven Spotless - apply
        entry: bash -c "cd smartvolt && mvn spotless:apply"
        language: system
        types: [java]
        always_run: true
