repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml        # Valida arquivos YAML
      - id: check-json        # Valida arquivos JSON
      - id: end-of-file-fixer # Garante uma linha em branco no final dos arquivos
      - id: trailing-whitespace # Remove espaços em branco no  final das linhas
