repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml          # Check yaml files for syntax errors
      - id: end-of-file-fixer   # Enforce a newline at the end of files
      - id: trailing-whitespace # Remove trailing whitespace
