Feature: Register Station

  Background: A user starts on the operator page
    Given I am on the operator page

  Scenario: ...
    When I ...
    When I ...
    When I ...
    Then I ...
    When I ...
    Then I ...

  Scenario: ...
    When I ...
    When I ...
    Then I ...
