name: CI Pipeline

# on:
#   workflow_run:
#     workflows: ["Build and Push Docker Image"]
#     branches: [dev]
#     types: 
#       - completed

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  REGISTRY: ghcr.io
  # IMAGE_VERSION: ${{ github.sha }}
  IMAGE_VERSION: latest

jobs:
  backend-sonarqube:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: smartvolt
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull built image
        run: |
          docker pull ${{ env.REGISTRY }}/tqs-smartvolt/tqs-smartvolt-backend:${{ env.IMAGE_VERSION }}

      - name: Build "test image" from build stage
        run: |
          docker build \
          --target build \
          -t ${{ env.REGISTRY }}/tqs-smartvolt/tqs-smartvolt-backend:${{ env.IMAGE_VERSION }} \
          --tag test-image \
          -f Dockerfile .

      - name: Build and run unit tests inside Docker
        run: |
          docker run --rm \
          --network host \
          test-image \
          sh -c "mvn -B package --file pom.xml"

      - name: Run integration tests inside Docker
        run: |
          docker run --rm \
          --network host \
          test-image \
          sh -c "mvn -B integration-test verify --file pom.xml"

      - name: Add code coverage information to PR
        id: jacoco-pr
        uses: madrapps/jacoco-report@v1.7.1
        if: github.event_name == 'pull_request'
        with:
          paths: |
            ${{ github.workspace }}/**/target/site/jacoco-merged-test-coverage-report/jacoco.xml
            token: ${{ secrets.GITHUB_TOKEN }}
            min-coverage-overall: 80
            min-coverage-changed-files: 80

      - name: Push code coverage information to SonarQube
        run: |
          docker run --rm \
          --network host \
          test-image \
          sh -c "mvn sonar:sonar -Dsonar.token=${{ secrets.SONAR_TOKEN }}"
