name: Deploy
on:
  # workflow_run:
  #   workflows: ["Commit Stage"]
  #   branches: [dev]
  #   types: 
  #     - completed
  push:
    branches: [main]

permissions:
  contents: read


jobs:
  on-success:
    runs-on: self-hosted

    
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Checkout SmartVolt repository
        uses: actions/checkout@v2
        # if:  github.event.pull_request.head.repo.full_name == github.repository
        with:
          submodules: true
          repository: TQS-SmartVolt/SmartVolt
          token: ${{ secrets.SMART_VOLT_SECRET }}

      - name: Deploy using Docker Compose
        run: |
          set -a
          source .env.production
          docker compose up -d --build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
