name: Deploy
on:
  workflow_run:
    workflows: ["Commit Stage"]
    branches: [dev]
    types: 
      - completed

jobs:
  on-success:
    runs-on: self-hosted

    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout additional repo
        uses: actions/checkout@v3
        with:
          repository: tqs-smartvolt/smartvolt
          token: ${{ secrets.GITHUB_TOKEN }}
          path: smartvolt

      - name: Deploy using Docker Compose
        run: |
          cd smartvolt
          set -a
          source .env.production
          docker compose up -d --build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
