name: Deploy
on:
  workflow_run:
    workflows: ["Staging"]
    branches: [main]
    types:
      - completed

permissions:
  contents: read

jobs:
  on-success:
    runs-on: self-hosted


    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout SmartVolt repository
        uses: actions/checkout@v2
        with:
          submodules: true
          repository: TQS-SmartVolt/SmartVolt
          token: ${{ secrets.SMART_VOLT_SECRET }}

      - name: Deploy using Docker Compose
        run: |
          set -a
          source .env.production
          docker compose down
          docker compose up -f compose.prod.yml -d --build
        env:
          DOCKER_PORT: 8080
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
