name: Deploy
on:
  pull_request:
    branches:
      - main
    types:
      - closed

permissions:
  contents: read

jobs:
  deploy-in-production:
    runs-on: self-hosted

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout AppConfig repository
        uses: actions/checkout@v2
        with:
          submodules: true
          repository: TQS-SmartVolt/AppConfig
          token: ${{ secrets.SMART_VOLT_SECRET }}

      - name: Deploy using Docker Compose
        run: |
          set -a
          source .env.production
          docker compose --file compose.prod.yml down
          docker compose --file compose.prod.yml up -d --build
          docker system prune -a -f
        env:
          DOCKER_PORT: 8080
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
