name: Deploy
on:
  # workflow_run:
  #   workflows: ["Commit Stage"]
  #   branches: [dev]
  #   types: 
  #     - completed
  push:
    branches: [main]

jobs:
  on-success:
    runs-on: self-hosted

    permissions:
      contents: read
    
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      -   uses: actions/checkout@v2
      -
      # - name: Checkout additional  repo
        if: github.event.pull_request.head.repo.full_name == github.repository
        uses: actions/checkout@v4
        with:
          repository: tqs-smartvolt/smartvolt
          token: ${{ secrets.ACCESS_TOKEN }}
          path: smartvolt

      - name: Deploy using Docker Compose
        run: |
          cd smartvolt
          set -a
          source .env.production
          docker compose up -d --build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
