name: Build and Push Docker Image
on:
  push:
    branches: ['main'] # TODO: change to `dev` and `release`
  pull_request:
    branches: ['main'] # TODO: change to `dev` ONLY

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/tqs-smartvolt/tqs-smartvolt-backend:latest
            ${{ env.REGISTRY }}/tqs-smartvolt/tqs-smartvolt-backend:${{ github.sha }}

      # NOTE: Paid Feature or Public Repositories Only
      # - name: Generate artifact attestation
      #   uses: actions/attest-build-provenance@v2
      #   id: attest
      #   with:
      #     subject-name: ${{ env.REGISTRY }}/tqs-smartvolt/tqs-smartvolt-backend
      #     subject-digest: ${{ steps.push.outputs.digest }}
      #     push-to-registry: true
