name: Staging

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend-sonarqube:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: smartvolt
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven

      - name: Build (skip unit tests)
        run: mvn -B package -DskipTests --file pom.xml

      - name: Run Complex Integration Tests
        run: mvn -B integration-test verify -Dgroups=complex --file pom.xml # @Tag("complex") -> JUnit 5

# Skip unit tests because it's already done in the commit stage

# Em paralelo: faco tambem o package para fazer os selenium e depois compilo para fazer os de performance
# Xray
