name: Quality Web Tests

on:
  push:
    branches-ignore: [main, dev]

env:
  REGISTRY: ghcr.io

jobs:

  web-quality-stage:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [public-pages, operator-pages, evdriver-pages]
    permissions:
      contents: read

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # - name: Checkout AppConfig repository
      #   uses: actions/checkout@v2
      #   with:
      #     submodules: true
      #     repository: TQS-SmartVolt/AppConfig
      #     token: ${{ secrets.SMART_VOLT_SECRET }}

      # - name: Log in to GitHub Container Registry
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ${{ env.REGISTRY }}
      #     username: ${{ secrets.GHCR_USERNAME }}
      #     password: ${{ secrets.GHCR_PAT }}

      # - name: Staging with Docker Compose
      #   run: |
      #     set -a
      #     sed -i '/^VITE_BACKEND_HOST=host\.testcontainers\.internal$/d' .env.staging   # Remove the line to run in localhost
      #     source .env.staging
      #     docker compose --file compose.stag.yml down
      #     docker compose --file compose.stag.yml up -d --build
      #     docker image prune -a -f
      #   env:
      #     DOCKER_PORT: 8080
      #     username: ${{ github.actor }}
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Change working directory
      #   run: cd ..

      - name: Checkout Frontend repository
        uses: actions/checkout@v2
        with:
          submodules: true
          repository: TQS-SmartVolt/Frontend
          token: ${{ secrets.SMART_VOLT_SECRET }}

      - name: Set up Node.js
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 14

      - name: Run Frontend Quality Tests
        working-directory: web-quality-tests
        run: |
          npm install
          npm install -g @lhci/cli@0.14.x
          npm run lhci:${{ matrix.target }}
